# -*- coding: utf-8 -*-
"""Exercises_US_Crime_Rates.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Qf7_GotRT5KnV9bclhyimqzK5tRQSFrr

# United States - Crime Rates - 1960 - 2014

### Introduction:
### Step 1. Import the necessary libraries
"""

import pandas as pd
import numpy as np

"""### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/Laxminarayen/Inceptez-batch-25-Classwork/refs/heads/main/Python-Class11-Pandas-Intermediate/US_Crime_Rates_1960_2014.csv).

### Step 3. Assign it to a variable called crime.
"""

url = "https://raw.githubusercontent.com/Laxminarayen/Inceptez-batch-25-Classwork/refs/heads/main/Python-Class11-Pandas-Intermediate/US_Crime_Rates_1960_2014.csv"
crime = pd.read_csv(url)

"""### Step 4. What is the type of the columns?"""

crime.dtypes

crime.head(5)

"""##### Have you noticed that the type of Year is int64. But pandas has a different type to work with Time Series. Let's see it now.

### Step 5. Convert the type of the column Year to datetime64
"""

crime['Year'] = pd.to_datetime(crime['Year'], format="%Y")

crime.dtypes

"""### Step 6. Set the Year column as the index of the dataframe"""

crime.set_index(crime['Year'])

"""### Step 7. Delete the Total column"""

crime.shape[0] # Rows

crime.shape[1] # columns

"""### Step 8. Group the year by decades and sum the values

#### Pay attention to the Population column number, summing this column is a mistake
"""

crime.head(5)

# creating a new column called Decade and appending to the dataframe
crime['Decade'] = crime['Year'].apply(lambda x:(int(str(x)[0:4])//10)*10)

crime.head(3)

crime.columns

crime[['Decade','Total', 'Violent','Property', 'Murder',
       'Forcible_Rape', 'Robbery', 'Aggravated_assault', 'Burglary',
       'Larceny_Theft', 'Vehicle_Theft']].groupby(crime['Decade']).sum()

# using the MAX function to find the population of the decade
crime['Population'].groupby(crime['Decade']).max()

"""### Step 9. What is the most dangerous decade to live in the US?"""

# creating a new local varible
max_total = crime[['Total']].groupby(crime['Decade']).sum().max()
# creating a new dataframe
crime_aggregate = crime[['Decade','Total', 'Violent','Property', 'Murder',
       'Forcible_Rape', 'Robbery', 'Aggravated_assault', 'Burglary',
       'Larceny_Theft', 'Vehicle_Theft']].groupby(crime['Decade']).sum()
crime_aggregate['Decade'] = crime_aggregate['Decade']//10 # this division is constant as each decade has 10 years
#find the max(TOTAL) from the new data frame
max_total = crime_aggregate['Total'].max()
crime_aggregate[crime_aggregate['Total'] == max_total]